blank_issues_enabled: true
contact_links:
  - name: Telegram Community Chat
    url: https://t.me/tools_community
    about: Ask questions and discuss with the community
  - name: Telegram Channel
    url: https://t.me/builders
    about: Follow updates and announcements
